# Generated by Django 4.2.16 on 2024-11-10 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='time',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='updated',
        ),
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
