# Generated by Django 4.2.16 on 2024-11-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_todo_time_remove_todo_updated_todo_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created_at',
            new_name='time',
        ),
    ]
